import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Comic_Neue} from 'next/font/google'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Comic = Comic_Neue(
  {
  variable: "--comic", // nome css
  subsets: ["latin"],
  weight: "300"
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${Comic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
